export const chapterActivities = {
  "1": [
    "Asignación de persona que diseña el Sistema de Gestión de SST- con soportes",
    "Afiliación al Sistema de Seguridad Social Integral",
    "Capacitación en SST",
    "Plan Anual de Trabajo",
    "Identificación de peligros; evaluación y valoración de riesgos",
    "Política de Seguridad y Salud en el Trabajo",
    "Archivo y retención documental del Sistema de Gestión de SST"
  ],
  "2": [
    "Asignación de persona que diseña el Sistema de Gestión de SST- con soportes",
    "Asignación de recursos para el Sistema de Gestión de SST",
    "Afiliación al Sistema de Seguridad Social Integral",
    "Conformación COPASST",
    "Funcionamiento del COPASST",
    "Conformación del Comité de Convivencia Laboral",
    "Funcionamiento del Comité de Convivencia Laboral",
    "Política de Seguridad y Salud en el Trabajo",
    "Plan Anual de Trabajo",
    "Archivo y retención documental del Sistema de Gestión de SST",
    "Informe sociodemográfico",
    "Restricciones y recomendaciones médicas laborales",
    "Identificación de peligros y evaluación y valoración de riesgos",
    "Entrega de los elementos de protección personal – EPP y capacitación en uso adecuado",
    "Simulacro de evacuación (Planeación, conteo, evaluación)",
    "Conformación Brigada de prevención, preparación y respuesta ante emergencias",
    "Revisión por la alta dirección"
  ],
  "3": [
    "Asignación de una persona que diseñe e implemente el Sistema de Gestión de SST- con soportes",
    "Asignación de responsabilidades en SST (Perfil de cargo firmado)",
    "Asignación de recursos para el Sistema de Gestión en SST",
    "Afiliación al Sistema de Seguridad Social Integral",
    "Identificación de trabajadores que se dediquen en forma permanente a actividades de alto riesgo y cotización de pensión especial",
    "Conformación COPASST",
    "Funcionamiento del COPASST",
    "Conformación del Comité de Convivencia Laboral",
    "Funcionamiento del Comité de Convivencia Laboral",
    "Reinducción SST",
    "Curso Virtual de capacitación de cincuenta (50) horas en SST- Personal",
    "Política de Seguridad y Salud en el Trabajo",
    "Objetivos de SST",
    "Evaluación Inicial del Sistema de Gestión",
    "Plan Anual de Trabajo",
    "Archivo y retención documental del Sistema de Gestión de SST",
    "Rendición de cuentas",
    "Matriz legal",
    "Mecanismos de comunicación",
    "Gestión del cambio",
    "Perfiles de cargos/ Profesiograma",
    "Comunicación al médico de los Perfiles de cargos/ Profesiograma",
    "Custodia de las historias clínicas",
    "Servicios de higiene",
    "Manejo de Residuos",
    "Registro y análisis estadístico de accidentes de trabajo y enfermedades laborales",
    "Identificación de peligros y evaluación y valoración de riesgos con participación de todos los niveles de la empresa",
    "Identificación de sustancias catalogadas como carcinógenas o con toxicidad aguda",
    "Mediciones ambientales",
    "Conformación Brigada de prevención, preparación y respuesta ante emergencias",
    "Simulacro de evacuación (Planeación, conteo, evaluación)",
    "Matriz- Definición de indicadores del Sistema de Gestión de Seguridad y Salud en el Trabajo",
    "Planificación de la auditoría con el COPASST",
    "Auditoría anual con soportes del auditor",
    "Revisión por la alta dirección. Alcance de la auditoría del Sistema de Gestión",
    "Acciones preventivas y/o correctivas",
    "Acciones de mejora conforme a revisión de la Alta Dirección",
    "Plan de mejoramiento"
  ]
};
